### ISSUE TITLE
Add RPM build

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta#1]
- [x] Add an inmanta.spec file that builds `python3-inmanta`, which follows the current `<year>.<minor>[.<patch>]` versioning. The RPM should require the `python3-inmanta-core` RPM and pin its version, similar to the `inmanta-service-orchestrator` spec file. It should also install the Python `inmanta` package (the one from this repo, not the source package) in `/opt/inmanta` (again, the `inmanta-service-orchestrator` spec file could be used as an example).
- [ ] Add an `inmanta-oss-release` and corresponding pyp and rpm build jobs on Jenkins, preferably by making the current `irt/ci/inmanta-core/` builds config-driven pipelines so they work for `inmanta-core` as well as `inmanta-oss`.

**Comment by bartv** [comment]
see #4

**Comment by andraskvr** [comment]
I'm closing this one as whatever was left to make the rpm pipeline fully work were split to different tickets
