### ISSUE TITLE
determine version numbers on the server instead of on the compiler

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta#1011]
Currently, the compiler determines the version number, this can cause all sort of trouble, such as out-of-order versions, duplicates,....

The server should assign the version number and ensure that version number are monotonically increasing.

**Comment by bartv** [comment]
This also causes problems with multiple compiles in the same second.

**Comment by wouterdb** [comment]
1- make version field 64bit
2- make sequencer in DB per env, initilialize on highest available
3- reject old compiler with warning

**Comment by bartv** [comment]
decommission_environment also allocates a version
