### ISSUE TITLE
Potential race in test cases

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta#1095]
There is a potential race in the test cases when setting a model to done

To improve test stability, the following steps should be taken

- [ ] in test_server_agent, use _wait_until_deployment_finishes (or alternatives) everywhere
- [ ] use model state to determine if done instead of resource count (this might be the race, as count is set just before the model state)
- [ ] ensure timeouts are set such that a redeploy by the agent can't happen in the timeout interval (if the race is in the code, some test case may only terminate after redeploy/repair, this should lead to failure)

**Comment by bartv** [comment]
@arnaudsjs can you review what has been fixed from this ticket?
