### ISSUE TITLE
Add API call to pause an agent

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#1128]
The agentmanager allows agents to be paused but this functionality is not exposed through an API.

**Comment by arnaudsjs** [comment]
@wouterdb @bartv When this API is called, should the agents be notified synchronously? Or should that happen in the background?

**Comment by wouterdb** [comment]
Good questions.

1. sync or async, I'm a bit undecided, I see no strong arguments. Perhaps safest to make it sync?
2. the external api? can we do `agent/{name}/pause` ?
3. for the server->agent api, can we do the same? (or would that be crazy talk?)

**Comment by arnaudsjs** [comment]
1. I agree. Sync would be the safest option, but I got no strong opinion on this.
2. I like this naming schema. Will we have an `agent/{name}/pause` and an 
    `agent/{name}/unpause` API call? Or make `agent/{name}/pause` parameterized? The 
    path `agent/{name}/pause` looks like an API call to pause an agent. If we parameterize it, I 
    would rather make it `agent/{name}/paused`? No?
3. The server->agent API call already exists. This one has the path `/agentstate`. Are we going 
    to update this one?
