### ISSUE TITLE
plugins should unwrap returns values of primitive types

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#1169]
A plugin with return type number[] returns a sequenceproxy

**Comment by wouterdb** [comment]
the compiler unwraps all values:

https://github.com/inmanta/inmanta/blob/master/src/inmanta/plugins.py#L356

Is it possible that this is an issue in the exporter? 
Could you provide some more context?

**Comment by wouterdb** [comment]
@bartv is this still open?

**Comment by bartv** [comment]
Yes, I need to find the example again that breaks this

**Comment by bartv** [comment]
I am going to close this one
