### ISSUE TITLE
Create server extension documentation

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#1209]
Add documentation how to create a server extension. This should also contain documentation protocol and database usage

- [x] Document how to create a new extension
- [x] Document the definition of new protocol methods + use of pydantic
- [ ] Document the use of the database layer
- [x] Create seed project

**Comment by wouterdb** [comment]
also mention overriding the modules_dir fixture

**Comment by bartv** [comment]
@wouterdb this can be closed, no?
