### ISSUE TITLE
Document base exception types and their purpose

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta#1210]
in the platform developer guide

This is about the various exceptions used internally in inmanta code base. The documentation doesn't have to be complete, but at least touch on the important categories (HTTP, Compiler, ...)

**Comment by sanderr** [comment]
`CompilerException` and children are already documented under `Inmanta Reference > Inmanta API reference > Compiler exceptions`. The documentation created for this issue should probably refer there.
