### ISSUE TITLE
Cleanup container image

### ISSUE THREAD

**Issue by edvgui** [inmanta/inmanta#124]
~The container image is not really inline with the state of the art.  Here is a list of things to address:~
1. ~`ENTRYPOINT` should be `/usr/bin/inmanta`~
2. ~`COMMAND` should be `-vvv --timed-logs server`~
3. ~`USER` should be `inmanta`/`993`~
4. ~Get rid of the `container-entrypoint-with-env.sh` file~
5. ~No need for sudo command in the container, and `inmanta` to be in the `sudo` group. (cf. https://github.com/inmanta/inmanta/issues/92)~

~These changes are impactful, they should not be done without proper consideration (for one thing, it would break the development flow of the solutions team as having sshd running alongside the server becomes undesirable with this setup)~

Following those changes, the `Install with Podman and Systemd` instructions should be updated (some options in the unit files can be removed --> more elegant)

-> in inmanta-core repo, for OSS and iso, on master

**Comment by sanderr** [comment]
Discussed in planning meeting and on Slack: only the very last sentence remains relevant. All the rest has been addressed in the native containers.

**Comment by sanderr** [comment]
Closed in favor of #8304
