### ISSUE TITLE
Implement if statement

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta#1325]
Currently, the only way of doing conditional logic is through conditional implemenation

An if statement would be nice to have.

notes for the implementer
- [x] create test case for syntax
- [x] create AST node (can be roughly based on `For`, ignore the methods for evaluation for now)
- [x] add to parser (look at [PLY](https://www.dabeaz.com/ply/) first), can be based on p_for
- [x] make syntax test case work
- [x] add semantics testcase 
- [x] implement AST node completely (based on `SubConstructor`)
- [x] make the testcase work

**Comment by bartv** [comment]
fixed
