### ISSUE TITLE
parsing issues when trying to compile files with slightly unusual characters

### ISSUE THREAD

**Issue by Frederik-Baetens** [inmanta/inmanta#1341]
Code examples with their error output:

Example 1:
```deployment2 = k8s::Deployment(
    var=é,
    )
```
```
Syntax error é,
    )

 ()
```
Example 2:
```
deployment2 = k8s::Deployment(
    name="hello-nginx2",
    var=🤔,
    cluster=cluster
    )
```

```
Syntax error 🤔,
    clu ()
```

Example 3:
```
é
```
```
'Lexer' object has no attribute 'lexmatch'
```

Example 4:
```
aé=66
```
```
Syntax error é=66

 ()
```
Example 5:
```
K8éééYamlResource.cluster [1] -- Cluster
```
```
Syntax error éééYamlRes ()
```

@bartv can i have half a pepper for 5 variations :thinking: ?

**Comment by sanderr** [comment]
What is the desired behaviour here? It seems like example 3 is a different case from the others since there's not a single match. I suppose an informative error message is in order there. For the other examples it's not so clear what is expected since they are actually syntax errors.

**Comment by Frederik-Baetens** [comment]
I think that better error messages for the other examples would also be nice. For example in example 2, it is pointed out that the emoticon is a syntax error, but it also prints `clu ()` which isn't ideal, because that's half of another line, and there's no problem with that line.

Also I think the empty brackets that are present in all examples except for the third, shouldn't be there because they don't seem to convey any information.

I think a good idea could be informing in which file the error was found, and printing the entire line where the error is found, and putting a pointer under the infringing character. Example from rustc:

```
error: incorrect close delimiter: `)`
 --> src/main.rs:2:30
  |
1 | fn main() {
  |           - un-closed delimiter
2 |     println!("Hello, world!"));
  |                                         ^ incorrect close delimiter
```

Ideally, more specific information about why a syntax error occured would be nice. In this case that would be information about which character are allowed in which language elements

**Comment by sanderr** [comment]
That seems like good advice, thanks. I'm not very familiar with the current lexer yet, but I'll investigate if something in that style is possible.

**Comment by wouterdb** [comment]
see also https://github.com/inmanta/inmanta/blob/87e1d86ddf344c51b204a657a092a12a87fe9a49/src/inmanta/parser/plyInmantaLex.py#L221-L234
