### ISSUE TITLE
Improve error message on missing imports in _init.cf

### ISSUE THREAD

**Issue by Frederik-Baetens** [inmanta/inmanta#1372]
When imports are missing in _init.cf, the error message just says `inmanta.ast.TypeNotFoundException: could not find type k8s::resources::Deployment in namespace k8s` (the type was used as the type of an argument in a plugin in the module)

The issue was that the type wasn't imported in _init.cf.

It would be nice to know where the type was used (in this case the plugin) and perhaps even what to do about it.

**Comment by sanderr** [comment]
duplicate of #1221, fixed in #1763
