### ISSUE TITLE
Support multiple api version methods on the same method

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#1416]
Inmanta protocol now has an version keyword in annotations. This work for 100% disjunct method definitions and handlers. This tickets add more flexibility to this model:

When sharing the same handler:
- Decorate a method multiple times with different versions
- Decorate a method multiple times with different versions and different parameters such as:
    - envelope/envelope key
    - other url
    - other mappers, ...
- ...

With different handler for each version:
- Use the same method definition but with different versions. Each version has a different implementation. The method itself has two method decorators, one for each version

Client:
- The current client will select the lowest version when a method has multiple versions available.
- A constructor parameter should allow the client to select the latest version or a specific version.

SessionEndpoint:
- with #1409 in place, session endpoint should select the newest version

**Comment by wouterdb** [comment]
@bartv  can this ticket be closed?
