### ISSUE TITLE
list type should not allow for entities in the list

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta#1435]
The following model should fail but doesn't
```
entity ListContainer:
	list lst
end

implement ListContainer using std::none

x = ListContainer()
x.lst = [x]
```

**Comment by sanderr** [comment]
@wouterdb @bartv what exactly should be allowed inside lists? Are only instances disallowed? Is `[[{"key": [1,2]}]]` for example a valid list? I assume the same goes for dicts?

**Comment by wouterdb** [comment]
that is indeed valid
