### ISSUE TITLE
Investigate race condition in test case

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta#1472]
Output test run:

[log.txt](https://github.com/inmanta/inmanta/files/3706138/log.txt)

**Comment by bartv** [comment]
@wouterdb You should take a look at this because I reminded me of the fix you made yesterday.

**Comment by wouterdb** [comment]
looks like a process that was not properly closed (i.e. await process.wait() or equivalent)  by a previous test, that crashed past the lifetime of its eventloop.

**Comment by wouterdb** [comment]
[consoleText.txt](https://github.com/inmanta/inmanta/files/3728938/consoleText.txt)
