### ISSUE TITLE
A failure to install handler code should mark resources as unavailable

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#1520]
When the installation of the handler code fails on the agent, the resources of that type stay in an available state.

When this fails a plain exception is raised:
https://github.com/inmanta/inmanta/blob/a4543ed64d7da03aa9a8e7b714dc5f4ae71276e2/src/inmanta/agent/agent.py#L1077

Depending on where this happens, a resource action update should be done for all resource of the failing type to mark them unavailable.

**Comment by wouterdb** [comment]
close in #1523
