### ISSUE TITLE
Support dict lookup in if statement

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#1573]
The following code is not supported by the parser:
```
x = {"a": true}

if x["a"]:

end
```

**Comment by sanderr** [comment]
@bartv
The following model, however, is allowed
```
x = {"a": true}

if x["a"] == true:
end
```
So the failure is expected, as
```
if true:
end
```
is invalid as well. I believe there is a ticket to fix this. @wouterdb mentioned it earlier today.

Should I add a better error message or would that be wasted effort since we're planning on allowing this soon?

**Comment by sanderr** [comment]
Discussion in person lead to the creation of #1804. After resolution of that ticket this one should be given a second look. It is true there is an inconsistency in the behaviour, since
```
if true:
end
```
is not accepted while
```
implement Test using i when true
```
and
```
t = true
if t:
end
```
are accepted

**Comment by sanderr** [comment]
conclusion after #1806: `true` as a condition is fixed now. Support for dict lookup in condition should be added to the parser.
