### ISSUE TITLE
python 3.8 test failures

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta#1608]
Some tests fail when using Python 3.8. Result from running tests on commit 267e125:

```
- tests/test_data.py:33 test_connect_too_small_connection_pool
- tests/server/test_incremental_deploy.py:377 test_deploy_scenarios_removed_req_by_increment2
- tests/server/test_incremental_deploy.py:315 test_deploy_scenarios
- tests/server/test_incremental_deploy.py:436 test_deploy_scenarios_added_by_send_event_cad
- tests/server/test_incremental_deploy.py:354 test_deploy_scenarios_removed_req_by_increment
- tests/server/test_incremental_deploy.py:199 test_deploy
- tests/server/test_incremental_deploy.py:411 test_deploy_scenarios_added_by_send_event
```

**Comment by kazaamjt** [comment]
Confirmed on both Debian and Arch

**Comment by sanderr** [comment]
First one has been fixed by #1872. No additional insights on the other ones yet, except that they seem somewhat random. It seems like it's not consistently the same tests failing.

**Comment by andraskvr** [comment]
With the latest changes, the tests with Python 3.8 seem to consistently pass on:

- Fedora 31
- Debian 10
- Ubuntu 18

**Comment by sanderr** [comment]
For me (Arch Linux) there are still some failing tests, but those are probably related to my postgres version.
