### ISSUE TITLE
publish pytest-inmanta-extensions in internal devpi on each build

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#1638]
Currently jenkins only publishes core to devpi and not the pytest extensions.

**Comment by kazaamjt** [comment]
Upload succesfull:
https://artifacts.internal.inmanta.com/inmanta/dev/pytest-inmanta-extensions/2019.6.dev201912131549
@bartv @Arnaud, could you review and close if approved?
Code:
https://jenkins.inmanta.com/job/core/job/inmanta-core/configure
