### ISSUE TITLE
when clause of implements does not allow fully qualified variable names

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#164]
`implement std::HostConfig using ubuntu when host.os == ubuntu::ubuntu1404`

does not work anymore and has to be replace with the more verbose:

`implement std::HostConfig using ubuntuCloudArchive when host.os.name == "ubuntu" and host.os.version == 14.04`

**Comment by wouterdb** [comment]
I tried reproducing it with

```
implementation linux for std::HostConfig:
end

implement std::HostConfig using linux when host.os == std::linux

std::Host(name="vm1", os=std::linux)
```

and that compiles perfectly.

Can you verify that this snippet fails for you?

Wouter

PS: Are you sure you imported the ubuntu module?
