### ISSUE TITLE
Ask for confirmation to overwrite the .inmanta file in cli tool

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta#1642]
A second run of the quickstart will fail, since the --save options of `inmanta-cli environment create` doesn't override a .inmanta file when it already exists. When the .inmanta file exists, ask for confirmation to overwrite it.

**Comment by bartv** [comment]
Or we should ask if they want to replace the file?

**Comment by wouterdb** [comment]
@kazaamjt can this issue be closed?
