### ISSUE TITLE
Remote agent with python fails silently

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#1692]
When the remote host (centos 8, recent ubuntu, ...) install python3 by default. The resources fail with a gateway error but only the agent.err log file show "python" command unkown.

fix:

- improve error message to clearly state that 
1. may be due to the machine being unavailable
2. or python being messing
3. which file to check for what log line when python isn't there

**Comment by kazaamjt** [comment]
Was able to reproduce this using an ubuntu-vm (ssh root-login enabled) and the quickstart (removed the 2 agents and replaced them with the ubuntu host)

under /var/log/agent-{agent-uuid}.err there should be a log:
`bash: python: command not found` as mentioned by the ticket

Unclear how to proceed:
- Make sure this doesn't fail silently?
- fallback on using `python3` if no `python` command is available

**Comment by bartv** [comment]
1. The failure should never be silent. Because a minimal centos 8 does not even contain python.
2. Fallback retry might be a good idea. We only have to decide on the order python or python3 first.
