### ISSUE TITLE
inmanta-cli seems to use HTTP/1.0 instead of HTTP/1.1

### ISSUE THREAD

**Issue by kazaamjt** [inmanta/inmanta#1740]
According to the tornado docs, the http client should be using HTTP/1.1, but testing with an Apache server revealed that it is using HTTP/1.0 instead:

`172.28.0.1 - - [28/Jan/2020:17:09:48 +0000] "GET / HTTP/1.0" 400 362 "-" "-"`

**Comment by wouterdb** [comment]
This should be verified
