### ISSUE TITLE
Include tags in the openapi definition

### ISSUE THREAD

**Issue by andraskvr** [inmanta/inmanta#1751]
The operations on the swagger-ui can be grouped by tags, to provide a better overview of the API.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#operation-object

The grouping can be done based on the method's properties, e.g.:
- core vs. extension
- topic
- api version
- etc.

**Comment by wouterdb** [comment]
@andraskvr could you formulate one or more proposals of how we could or should group them

**Comment by andraskvr** [comment]
Maybe the most useful would be to group them by the resources the endpoints represent. For example group everything that deals with Projects in one category, another one for Environments, similar to the grouping of the example application: https://petstore.swagger.io/#/

**Comment by wouterdb** [comment]
ok, that seems like a good idea

**Comment by wouterdb** [comment]
For now: do it by slice
