### ISSUE TITLE
infinite recursion in TypedList.type_string()?

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta#1758]
https://github.com/inmanta/inmanta/blob/592faa8f98334b77de17cf05945d0cc79952880c/src/inmanta/ast/type.py#L356

I believe this line is meant to call `self.basetype.type_string()`

**Comment by sanderr** [comment]
Also, the rest of this class seems weird. Why does it not inherit from `List`, or at the very least `list`? The `__str__` implementation seems strange as well. I'm willing to fix this but I'd like confirmation first that I'm not just overlooking things.

**Comment by wouterdb** [comment]
It is a lot like lit, but has some crucial differences 

see higher in the file
https://github.com/inmanta/inmanta/blob/592faa8f98334b77de17cf05945d0cc79952880c/src/inmanta/ast/type.py#L69-L90

The bugs you spotted are indeed bugs

**Comment by sanderr** [comment]
Looking at the comment and the usage of `TypedList` I don't see how inmanta instances are an instance of the python type. Is it possible `TypedList` actually belongs in category 4?
I'll process this issue together with #1435 since it heavily depends on this.
