### ISSUE TITLE
Add type conversions to the language for primitive types

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#1798]
Support type conversions for number, integer, float and string. Example syntax:

```
value = integer("9")
```

**Comment by sanderr** [comment]
@bartv, @wouterdb, how should we handle discrepancies between Inmanta and Python values? For example, in Python `str(True)` would result in `"True"`, should `string(true)` in Inmanta result in `"true"` then, or is `"True"` acceptable?

**Comment by wouterdb** [comment]
it should be true, so that it is round-trip compatible

**Comment by sanderr** [comment]
It's round trip compatible either way.

**Comment by bartv** [comment]
but also for the user, so it should be true and not True
