### ISSUE TITLE
inconsistent scoping in if body

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta#1805]
This is a valid model
```
x = 42
if true:
        x = 0
end
```
while this is not
```
entity A:
        number n
end
implement A using std::none

x = A(n = 42)
if true:
        x.n = 0
end
```

This is inconsistent. It seems to me like the second behavior is the desired one: variables in an if body should not shadow existing ones.

**Comment by wouterdb** [comment]
It is not inconsistent pre-se: 

- relations and attributes are explicitly declared, implicit declaration doesn't work
- for local variables, assignment is (implicit)declaration, visible only in that scope/block. 

```
x = 0
```
is assignment to a local variable

```
x.n = 0
self.x = 0
```
is assignment to an attribute

However, it is a good idea to have warnings when shadowing local variables, as it is confusing

**Comment by sanderr** [comment]
You're right, I was mistaken. I'll close this issue since a ticket for the warning message already exists.
