### ISSUE TITLE
weird behavior with conditionals and non-bool variables

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta#1808]
```
str = "some_string"
if str and true:
    std::print(True)
end
```

prints `True`. The same goes for `str = ""`, `str = null` etc. What's the desired behavior here? I'm of the opinion we should only accept actual booleans.

**Comment by wouterdb** [comment]
Agreed, only accept real booleans

@bartv  can you confirm

**Comment by bartv** [comment]
yes

**Comment by wouterdb** [comment]
@bart 
We may have to add a flag to keep backward compatibility on this? wdyt?
