### ISSUE TITLE
duplication between type constraint and model variable

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta#1809]
The following model is not valid since `bandwith_profiles` can not be resolved in the `direct_execute()` of the type check
```
bandwidth_profiles = {
    "50Mbps":  50000,
    "100Mbps": 100000,
}
typedef aws_speed_t as string matching self in bandwidth_profiles

entity Test:
    aws_speed_t speed
end
implement Test using std::none

x = Test(speed="100Mbps")
```

This seems a limitation in the language. Code duplication is currently needed if the bandwidth profiles are required for the type check, as well as elsewhere in the model. The goal of this ticket is to gather possible approaches that would benefit this use case, and hopefully the language in general.

Some high level options without regard for feasibility or usefullness:

0. Schedule type validations like we do statements, so variables can be resolved in a type check.

1. Introduce an enumeration type and add a dict-like structure that is a total relation between an enumeration domain and any codomain (so we can pattern match). For example:
```
typedef aws_speed_t as enum ["50Mbps", "100Mbps"]

# some type declaration would be required: aws_speed_t -> number
bandwidth_profiles = {
    "50Mbps":  50000,
    "100Mbps": 100000,
    # needs to be a total relation: compiler check
}
```

2. Introduce annotation for static definitions, similar to `#define` in C. These can then be scheduled before main execution so they are available in `direct_execute` as well as during `execute`

I personally like option 1, though I think it still needs some refinement .

**Comment by wouterdb** [comment]
3.  perform constant propagation to allow constant expression (i.e. with empty requires set and no type references inside) to be used in the type checker.

**Comment by wouterdb** [comment]
@sander: what do you think of option 3?

**Comment by sanderr** [comment]
I'm not sure I see how propagation would work? For example, the statement
```
bandwidth_profiles = {
    "50Mbps":  50000,
    "100Mbps": 100000,
}
```
is an assign statement with a non-empty requires set: the dictionary, which is itself a statement with a nonempty requires set: the literals. So there's a chain of dependencies, same as with any statement. It seems to me that any attempt at propagation would result in something very similar to option 0, but maybe I'm missing something.

**Comment by wouterdb** [comment]
I mean, an optimizer that performs constant propagation prior to execution.

bandwidth_profiles would become a constant

**Comment by sanderr** [comment]
But what exactly would be the difference between this propagation and standard execution? Would it be a single pass before the scheduling starts?

**Comment by wouterdb** [comment]
Yes, exactly, it would package e.g. list literals into a single literal list instead of a list of literals, .... 

(would in general improve performance of enums)

**Comment by sanderr** [comment]
But in the example it's assigned to a variable. How would you propagate the literal to that value? The only thing I can think of is to try a `direct_execute` on all `Assign` statements.

**Comment by wouterdb** [comment]
It is indeed a limitation of the language.

I think all options are more complicated than the problem they solve. 

I want typing to remain a process that is guaranteed to be finite and deterministic, so that excludes 0. 
Option 1 doesn't actually reduce duplication (observe the example), and is very vague. (A simple unit test can give the same guarantees)
Option 2 will open the gates to hell (M4 is a surprisingly powerful and utterly unreadable programming language imho)  
Option 3 is too far of in the future.

**Comment by sanderr** [comment]
I agree that option 1 does not get rid of duplication, instead it makes it safe. But I do get your point on all the options. It might be more feasible to approach it from the other direction. We could allow binding to a variable in a typedef:
```
typedef aws_speed_t as string matching self in bandwidth_profiles@{
    "50Mbps":  50000,
    "100Mbps": 100000,
}

std::print(bandwidth_profiles)
```
I think it wouldn't be too hard to achieve, and it reduces the duplication. On the other hand it might not be very transparent since it's essentially a variable injected in the context from one of its statements (not an enclosing context like for a loop variable or a function definition). But in a loosely ordered data flow oriented language that might actually be acceptable.

**Comment by wouterdb** [comment]
or, to have it more pythonic (https://www.python.org/dev/peps/pep-0572/) 

```
typedef aws_speed_t as string matching self in bandwidth_profiles:={
    "50Mbps":  50000,
    "100Mbps": 100000,
}
```

That is actually feasible but it still is a very complicated solution to solve a very minor issue (you have to take into account that, in order to read code, you need to know all the language features used, so it adds a real cost to learning the language and becoming productive in it)

**Comment by sanderr** [comment]
The conclusion for this ticket seems to be to leave it as is. Agreed?

**Comment by wouterdb** [comment]
Agreed
