### ISSUE TITLE
plugin kwargs not passed when emits_statements option is true

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta#1833]
[This conditional branch](https://github.com/inmanta/inmanta/blob/9beb0eb11d6887b317cf0778f56fcf9ebc5ebcf9/src/inmanta/ast/statements/call.py#L130-L131) seems incorrect. I believe kwargs should be passed there as well, but I'm not sure. @wouterdb, what is the `emits_statements` option of a `Plugin`?

**Comment by wouterdb** [comment]
please deprecate this option

**Comment by wouterdb** [comment]
But this branch is indeed not correct
