### ISSUE TITLE
Config section compiler_datatrace not defined

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta#1916]
When running the compiler, it shows the following warning: `Config section compiler_datatrace not defined`. It seems that the `compiler_datatrace.enable` option is used, but never defined.

**Comment by wouterdb** [comment]
You need to create an Option object in one of the config modules   (https://github.com/inmanta/inmanta/blob/master/src/inmanta/config.py#L246 )

The preferred way of getting/setting the options is through the option object, as it does input validation and default values.

The document generator collects these options objects to generate docs. If you make a new config module for the compile, add it here (https://github.com/inmanta/inmanta/blob/master/docs/reference/config.rst) to have the doc generator pick it up.

**Comment by sanderr** [comment]
I think I see what needs to be done. However, I'm a bit confused about the existing `compiler_rest_transport` section, since I don't see any options declared for it anywhere. Should this not be declared in `compiler/config.py` as well?

**Comment by sanderr** [comment]
Also, now that I've got a better grasp of what those sections actually mean I think it might be better to move the data trace option from the current dedicated `compiler_datatrace` section to a more generic `compiler_options` section. What do you think @wouterdb?
