### ISSUE TITLE
release_version agent trigger method disables incremental deploy

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#2025]
When the server has auto deploy disabled each version has to be released manually through the command line (cli tool or inmanta export -d) or the dashboard. They all use the release_version API call. The default for this call is None. When None is set it does a full deploy, effectively making it impossible with the current tooling to do an incremental deploy when the auto deploy is disabled.

A possible solution is to give the user an option on the cli and dashboard to choose the deploy but anyhow the current default is quite confusing.

The server already has a setting for the trigger method auto deployed versions (`agent_trigger_method_on_auto_deploy`). My proposal is to:

- Create a new setting `agent_trigger_method` that is the global setting for all agent on the environment. `agent_trigger_method_on_auto_deploy` could just override the default or it just deprecated
- `release_version` support incremental and deploy explicitly. When none is provided, the value of `agent_trigger_method` is used.

**Comment by wouterdb** [comment]
In fact, the CLI currently does an incremental deploy when doing `--push` without passing `--full` (same as export -d)

This could be confusing with the proposed changes. 

Appart from that, I think this is a good proposal.
