### ISSUE TITLE
Add documentation regarding the types of the config options

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta#2072]
The documentation regarding the different configuration options (https://docs.inmanta.com/community/latest/reference/config.html) adds a type to each config option, but never mentions how a specific type should is represented in a config file.

For example:
* Representation of a type list -> comma-separated list
* Representation of type dict -> comma-separated list of "key=value" pairs
* Representation of type time
* ...

Next to that, the time type is quite confusing. If something has the type time, I would expect the format "HH:mm[:ss]", but in fact it's just an integer. 

**Question:** Do we remove the time type?

**Comment by wouterdb** [comment]
I think the time type is there to indicate that the number is in seconds, but it should also get a better description.

**Comment by wouterdb** [comment]
(This could be updated by changing the docstring for the validator: https://github.com/inmanta/inmanta/blob/master/src/inmanta/config.py#L203)
