### ISSUE TITLE
Agent keeps deploying while paused

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta#2077]
* The pause() method in `inmant.agent.agent.Agent::pause()` disables the deploy and repair timers and prevent new update triggers, but doesn't cancel an ongoing deploy.
* The method `inmanta.server.agentmanager.AgentManager::_get_session_to_failover_agent()` doesn't take into account whether an agent is paused or not. 
* Verify that `inmant.agent.agent.AgentInstance` checks `is_enabled()` in methods that should not run when the agent is paused.

**Comment by wouterdb** [comment]
Also add test to ensure that a secondary doesn't take over when primary is paused.

**Comment by wouterdb** [comment]
Should go into hotfix  release 2020.2.1
