### ISSUE TITLE
Log primary agent correctly when pausing/unpausing agents

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta#2079]
* A paused agent doesn't have a primary agent. This should be logged in the database. 
* When an agent is unpaused, a new primary is elected. This should be logged in the database. 

See: `_pause_agent()` and `_unpause_agent()` methods in `inmanta.server.agentmanager.AgentManager`

**Comment by wouterdb** [comment]
Should go into hotfix release 2020.2.1
