### ISSUE TITLE
Improve changelog format

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta#2084]
I like the way that openstack does it for each of its components. A propose list of "sections" that we than also apply to the ISO3 release which should be a consolidated changelog of all extensions and modules. However, to also include module we need more automation otherwise to much time needs to be invested.

These are all possible sections, when they are empty we should leave them out.

Openstack provides (https://docs.openstack.org/releasenotes/nova/ussuri.html):

- [x] Template to internal docs
- [x] Add to core after release

# Release v1.2.3
## Release notes 

This section provides a short description of the most notable things. For example:

This release includes many new features, bug fixes and various performance improvements:
 
- a 
- b
- c

## New features

List of things added

## Known Issues

List of important known issues

## Upgrade notes

Any upgrade notes. We should probably add something here about backing up the database before upgrading, bla bla bla

## Deprecation notes

Any things that are deprecated. We should keep everything deprecated here until they are removed.

## Bug fixes

List of fixed bugs.

## Other notes

Everything that does not fit under one of the other categories.

**Comment by arnaudsjs** [comment]
This one was already done (see: https://docs.internal.inmanta.com/topics/irt/releasenotes.html)

**Comment by arnaudsjs** [comment]
@bartv I can close this one?

**Comment by bartv** [comment]
ok
