### ISSUE TITLE
Exporter fails when attribute contains a dict with proxy value

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#2121]
If a resource entity has an attribute `string[] attributes` and the following code in the exporter:

```
    def get_attributes(_, obj):
        return {
            "test": obj.attributes
        }
```

The export will fail on:
```
inmanta.util             ERROR    Unable to serialize @['a', 'b', 'c']
@['a', 'b', 'c'] is not JSON serializable
```

This is because the exporter does not unwrap any nested dynamic proxy values. There are multiple solutions to this:

- Just document this and the developer needs to handle this
- Try to find nested instances even though the attribute has no dyn proxy type
- Enforce attribute getters to always return dyn proxy instances (possibly breaking)
- Learn the json serializer to handle dyn proxy instances
- Make dyn proxy instances serializeable

# Conclusion after discussion
`{"test": obj.attributes}` is no dynamic proxy type, therefore it isn't converted by `Resource.map_field()`. It does however contain a dynamic proxy instance (`obj.attributes: DictProxy`). The simplest generic solution is probably to make dynamic proxy instances that should be allowed in that context serializable. This means at least `DictProxy` and `SequenceProxy`. This will probably make `inmanta.resources.serialize_proxy()` obsolete.

**Comment by sanderr** [comment]
Did you test this on `master`? I had the impression that the current implementation of `DynamicProxy.unwrap()` does do recursive unwrapping.

**Comment by sanderr** [comment]
I've looked at it again and it seems like there is a bug there though I'm not sure it's related. We recurse on `list` and `dict` but not on `DynamicProxy` itsself. See `src/inmanta/execute/proxy.py:85`. Could you try changing that line to `return cls.unwrap(item._get_instance())` and see if that resolves the issue?

**Comment by bartv** [comment]
> I've looked at it again and it seems like there is a bug there though I'm not sure it's related. We recurse on `list` and `dict` but not on `DynamicProxy` itsself. See `src/inmanta/execute/proxy.py:85`. Could you try changing that line to `return cls.unwrap(item._get_instance())` and see if that resolves the issue?

No, it does not fix the issue.

**Comment by sanderr** [comment]
I'll create a seperate ticket for that then. I'm looking into this a bit further to be able to answer your question but I'm new to the export logic. Could you maybe provide the full python snippet you used so I can fully understand the issue?

**Comment by bartv** [comment]
I created a quick hack to test this:
main.cf
```
host = std::Host(name="test", os=std::linux)
std::ConfigFile(host=host, path="/tmp/x", content="", attributes=["a", "b", "c"])
```

Changes to std:

```diff
diff --git a/model/_init.cf b/model/_init.cf
index 0926fc7..da21db9 100644
--- a/model/_init.cf
+++ b/model/_init.cf
@@ -237,6 +237,7 @@ entity File extends Reload, PurgeableResource:
     bool purge_on_delete=false
     bool send_event=undef
     string content_seperator="\n"
+    string[] attributes
 end
 
 implement File using reload, fileHost
diff --git a/plugins/resources.py b/plugins/resources.py
index 9e5c948..335e184 100644
--- a/plugins/resources.py
+++ b/plugins/resources.py
@@ -104,8 +104,13 @@ class File(PurgeableResource):
         A file on a filesystem
     """
 
-    fields = ("path", "owner", "hash", "group", "permissions", "reload")
+    fields = ("path", "owner", "hash", "group", "permissions", "reload", "attributes")
     map = {"hash": store_file, "permissions": lambda y, x: int(x.mode)}
+    
+    def get_attributes(_, obj):
+        return {
+            "test": obj.attributes
+        }
 
 
 @resource("std::Directory", agent="host.name", id_attribute="path")
```

**Comment by sanderr** [comment]
Ok, I understand what's going on. To finally answer your question: I would prefer a full conversion between one value domain and the other. This means recursing. Sadly, it's not that simple because the function might return any data structure (unlike plugins), as long as it's serializable. Since we don't know how to recurse on any data structure, I think the last option, making DynamicProxy instances serializable, is the best alternative.

**Comment by wouterdb** [comment]
We don't actually want DynamicProxy instances serializable, as they have relations. They can potentially pull the entire model with them. A developer making this mistake could blow an orchestrator out of the air, because suddenly every resource has the size of the complete model.

We could make the Sequence and Dict proxy serializable

**Comment by wouterdb** [comment]
@sanderr could you formulate an action plan based on the discussion
