### ISSUE TITLE
dynamicproxy not unwrapped recursively.

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta#2122]
`DynamicProxy.unwrap` recurses on `list` and `dict` but not on `DynamicProxy`. I believe it should.

**Comment by wouterdb** [comment]
Could you be more clear what this would mean? unwrapping a dynamic proxy means getting the instance out, how would this be done recursively? 

(the instance, being immutable, will always be an object in the compiler's native domain?)

**Comment by sanderr** [comment]
You're absolutely right. I think we could catagorize this a brain fart.
