### ISSUE TITLE
Add documentation about the evaluation of regex-based types

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta#2214]
Currently the language reference describes that a new type can be defined using a python regex. The documentation should also provide documentation on how this regex will be evaluated.

**Comment by wouterdb** [comment]
could you make this more concrete? I assume it will be evaluated as a python regex?

**Comment by arnaudsjs** [comment]
Once you have compiled a regex, you can evaluate it in different ways:
* re.search()
* re.match()
* re.fullmatch()
* ...

The way the regex is evaluated also has implications on how the regex should be written. For example: we use `re.match()` in our evaluation. This means that it's very important to put `$` at the end of the regex if you want it to be a full match. If `fullmatch()` was used this would not be required. Currently, the only way to know about this, is diving into the source code.
