### ISSUE TITLE
Clean up jenkins module project.

### ISSUE THREAD

**Issue by kazaamjt** [inmanta/inmanta#2247]
The std and lsm module have, at the time of writing, some branches that are still on the old system.
While the modules will slowly migrate on their own as existing PR's get closed.

Once all current PR's are closed, we should:
- Delete the old projects
- Rename the "-ci" projects

The following modules still need to be done:

- [x] aws
- [x] openstack
- [x] std
- [x] lsm

**Comment by arnaudsjs** [comment]
@andraskvr For your review.

**Comment by andraskvr** [comment]
Confirmed that all of these projects use the new system and pass. Approved, @arnaudsjs
