### ISSUE TITLE
Prepare for the pip-pocalypse

### ISSUE THREAD

**Issue by kazaamjt** [inmanta/inmanta#2268]
Pip has started warning about a new way to resolve dependencies:
> ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
flake8 3.7.9 requires pycodestyle<2.6.0,>=2.5.0, but you'll have pycodestyle 2.6.0 which is incompatible.
flake8 3.7.9 requires pyflakes<2.2.0,>=2.1.0, but you'll have pyflakes 2.2.0 which is incompatible.

Concretely we should look in to the possible fallout of this using --use-feature=2020-resolver and get ahead of this before it becomes an issue.

- [x] Investigate what this means
- [x] estimate potential impact
- [x] formulate plan and ticketize

**Comment by arnaudsjs** [comment]
**Remaining issue:** A version conflict exists for the docutils dependency in the aws module. The aws module pins the dependency to `docutils==0.16`, while the botocore dependency pins that same dependency to `docutils<0.16 and >=0.10`. Issue boto/botocore#1942 exists to resolve this issue.

**Comment by arnaudsjs** [comment]
The issue on the aws module is resolved now using botocore version 1.18.0.
