### ISSUE TITLE
Requirements parser doesn't support environment markers

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta#2359]
**Problem description:**

When an environment marker is present in the requirements.txt file of a module, that marker is removed by the requirements parser. Consider the following requirementx.txt file:

```
dataclasses~=0.7;python_version<'3.7'
```

The requiremements parser (see: `inmanta/env.py::VirtualEnv`) will translate this to:

```
dataclasses~=0.7
```

This causes issues when Inmanta is run on python version 3.7+. 

**How to reproduce:**

Run the test case `tests/test_deploy.py::test_deploy` using python 3.7+

**Comment by sanderr** [comment]
More specific cause: `inmanta.env.VirtualEnv._gen_requirements_file` calls `pkg_resources.parse_requirements` but ignores the result's `marker` attribute.

**Comment by wouterdb** [comment]
Things to try: pass multiple -r options, so we don't have to merge ourselves.

**Comment by wouterdb** [comment]
timeboxing: 1h or move to icebox
