### ISSUE TITLE
DuplicateException additional info not in msg attribute

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta#2473]
`DuplicateException.format()` adds "(original at ...) (duplicate at ...)". This is not part of `DuplicateException.msg`, which is used by `DuplicateException.export()`. This causes the error in the compile data exported by the compiler (or generated by the inmanta language server) to be less informative than it could be. This could easily be fixed by adding this additional information to `msg` or by overriding `CompilerException.export`.

**Comment by wouterdb** [comment]
I would not mix the separate meta-data into the message, as that makes it impossible to separate it again (e.g. in an IDE you want the error to be shown at the location, but not with the location repeated in the message)

**Comment by sanderr** [comment]
That's a valid point. I think this could be mostly solved by inmanta/vscode-inmanta#27. I'll close this one.
