### ISSUE TITLE
Sphinx version 3.3.0 breaks the link check

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta#2495]
**Problem:**

Sphinx version 3.3.0 makes the link check on the documentation fail (Run: `tox -r -e docs`). For this reason the sphinx dependency is currently pinned too version 3.2.1.

**Tasks:**

- [x] Investigate why the link check fails for sphinx version 3.3.0 and fix the issue
- [ ] Ensure that  dependency  bumps the sphinx dependency again by removing it from the ignore list in `.github/dependabot.yml`

**Question:**

This issue could have been prevented, by running `tox -r -e docs` on each dev branch. Running this check takes <2 minutes, which isn't a lot. We could even adjust to pipeline as such that this check only runs for branches for which the name matches the pattern `dependabot/pip/*sphinx*`. Any opinions?

**Comment by bartv** [comment]
We used to have the check, but removed it because CI times were to slow.
