### ISSUE TITLE
Add paging support to the /agentproc and /agent API call

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta#2500]
**Problem:**

The `/agentproc` and the `/agent` API call don't have paging support. As such, this query could push the Inmanta server out of memory when the database contains a lot of records.

**Comment by wouterdb** [comment]
make this similar to the other paged requests like compilereport.

**Comment by edvgui** [comment]
This will break backward compatibility right? Or should it be implemented in v2 of the api?

And just to be sure, for the pagination it should become something like this: https://phauer.com/2015/restful-api-design-best-practices/#keyset-based-pagination-aka-continuation-token-cursor ? Or what compilereport does is enough?
