### ISSUE TITLE
add support for LDAP authentication

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta#252]

**Comment by wouterdb** [comment]
interesting examples

https://github.com/gmr/tinman/blob/master/tinman/auth/ldapauth.py
https://code.gramener.com/s.anand/gramex/blob/12924cd310f50bc51b0c84e7d2d0faa3d0202c7c/gramex/handlers/authhandler.py


security guidelines:
http://www.tornadoweb.org/en/stable/guide/security.html

**Comment by bartv** [comment]
Auth has been completely externalized with JWT.
