### ISSUE TITLE
Add index syntactic sugar

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#394]
Add the ability to m:n navigate relations using keys. The index mechanism can be used to define what the keys are. For example:

```
vm = ip::Host(...)
file = std::File(host=vm, path="/etc/motd", ...)

vm.files["/etc/motd"]
```

**Comment by wouterdb** [comment]
how do we select the index to use?

The type to search for and first paramter are easy, the name of the second parameter is a problem

given | a.b[c] | vm.files["/etc/motd"]
------------|---------------------------|------------------------
type |  a.get_type().get_attribute(b).get_type() | File
first parameter name| a.get_type().get_attribute(b).name | host
first parameter value| a | vm
second parameter name| ? | path
second parameter value| c | "/etc/motd"

Perhaps the sanest solution is to only allow this syntax on type in which there is no confustion, the question is, how strict are we?

We could allow ony type with:
1. exactly one index
2. only one index with as first member the a.get_type()
2. only one index with as first member the a.get_type() and as second type c.get_type()
