### ISSUE TITLE
Deprecate default constructors

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#402]
With the addition of default values and undef for attributes, the constructor typedef is no longer required and should be deprecated.

**Comment by wouterdb** [comment]
we don't have a deprecation mechanism yet, what is the desired behavior?

print a warning? 
print a warning and give specific return value? 
print a warning with and option to supress?

**Comment by wouterdb** [comment]
this will create problems with indices on e.g. ConfigFile

**Comment by wouterdb** [comment]
- [ ] create error/deprecation reporting interface
- [ ] pass error reporter to typing and attach to queuescheduler
- [ ] update default constructor to emit deprication warning

**Comment by sanderr** [comment]
revised steps:
- [ ] produce `CompilerDeprecationWarning` at `Default` construction.
- [ ] test warning by using `typedef MyType as SomeEntity(somefield = "somevalue")`
- [ ] create issue for removing support for default constructors
