### ISSUE TITLE
Proxy unwrapping does not happen recursively

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#405]
When a plugin returns a list of entities, only the list is unwrapped out of the proxy. This results in error like:

```
  File "/home/bart/workspace/inmanta/src/inmanta/ast/variables.py", line 97, in resume
    raise RuntimeException(self, "can not get a attribute %s, %s not an entity" % (self.attribute, obj))
inmanta.ast.RuntimeException: can not get a attribute name, @state::State 7fbaa2ae1c18 not an entity (reported in st.name)
```

**Comment by wouterdb** [comment]
what should the behavior be here if the list itself is not a dynamic proxy?

for example

```
@plugin
def select_adults(person_list: "list") -> "list":
   return [person for person in person_list if person.age > 18]
```

Here the list returned is not a dynamic proxy, the items within are. 

A few things to consider:

1. returning complex data types from functions is tricky. The compiler accepts any python object as a value from a function, but this may render the compiler unstable (as this issue clearly shows) or create type errors at a later stage
2. we can not unwrap arbitrarily complex objects.
3. we can make it the responibility of plugin writer to properly unwrap complex objects
4. we can unwrap certain specific object (e.g. lists and dict)
5. we could improve the type checking of return values (also support list and dict with generics) but this would not necessarily improve stability, as we do most type checks dynamically, when the value is assigned.

**Comment by bartv** [comment]
The example above will be wrapped when it returns.

**Comment by wouterdb** [comment]
where in the code? (can't find it)
