### ISSUE TITLE
Openstack instance is killed if Update & Recompile is ran

### ISSUE THREAD

**Issue by automate-solutions** [inmanta/inmanta#448]
I initially deployed an OpenStack instance through an Inmanta deployment. I created a new project, a new environment and associated a private Github repository to it. The first deployment went just fine and it deployed the OpenStack instance as expected.
If I try to update and recompile the environment, it deletes the previously deployed OpenStack instance.
Unfortunately, I don't find any trace of that deletion in Inmanta's logs but I found them on OpenStack:
```
2017-07-03 10:43:58.843 3622 INFO nova.osapi_compute.wsgi.server [req-5826cc21-3f35-4f39-93b3-889e50140e09 a83b3f3df3974f54b91e9a6210ed7d8e 5878aebf371d4df3aa5bcb0cc6456720 - default default] 172.16.75.169 "DELETE /v2.1/5878aebf371d4df3aa5bcb0cc6456720/servers/b7754f21-cbce-4025-aef6-fa6b195e482d HTTP/1.1" status: 204 len: 339 time: 0.2463460
```
Is it an expected behavior?

**Comment by automate-solutions** [comment]
I completely reinstalled the VM that runs Inmanta and I can't reproduce the issue.
I guess that it could be due to the number of tests with the same values passed to the server/agent names and so on...

**Comment by bartv** [comment]
If you compile a new model and the resource is no longer available in the model the server will emit a resource with purged is true, if purge_on_delete is set to true for the previous version of the resource.

iirc all openstack resources are subclasses of std::PurgeableResource with purge_on_delete set to true

https://docs.inmanta.com/community/2017.2dev/reference/modules/std.html#entity-std::PurgeableResource
