### ISSUE TITLE
python3-iplib pip requirement is transformed to a private unaccessible/unavailable egg file

### ISSUE THREAD

**Issue by automate-solutions** [inmanta/inmanta#450]
The original `requirements.txt` file in `ip` module:
```
iplib@git+https://github.com/bartv/python3-iplib
```
Here is the generated `/tmp/tmpxxxxx` file that is used to install all required python packages with pip:
```
[root@inmanta ~]# cat /tmp/tmp5vo59681 
Jinja2 == 2.8.0
git+https://github.com/bartv/python3-iplib#egg=iplib
```
I guess that:
• The `.egg` is missing
• Or this line [https://github.com/inmanta/inmanta/blob/348e960e13c26d56f2cb36527e7665110016bfa1/src/inmanta/env.py#L106](inmanta/env.py) adds an extra `#egg` in between

**Comment by bartv** [comment]
This was a really stupid mistake from my side. I was cleaning up my personal github repos and I deleted this repo. I think for that reason pip asked for credentials.

The use of the @ and the rewrite to #egg is now added to the documentation (4c2d048)
