### ISSUE TITLE
Attribute redefinition only checks one level up

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#484]
```
typedef type as string matching self == "component" or self == "package" or self == "frame"

entity Node:
    type viz_type
end

entity Group extends Node:
end

entity Service extends Group:
    string viz_type="package"
end

entity Component extends Node:
    string viz_type="component"
end
```

The compiler shows an error for Component which redefines viz_type from **type** to **string**. It does not complain for Service which does the same. If Component inherits from Group, no error is provided.

**Comment by wouterdb** [comment]
fixed by 776264bba301f158c6f62a52c7643ea28812ed0d
