### ISSUE TITLE
Documentation offline

### ISSUE THREAD

**Issue by cnf** [inmanta/inmanta#491]
http://inmanta.readthedocs.io gives a 404, which means all documentation referenced here is unavailable.

**Comment by bartv** [comment]
The documentation building process became a bit to complex for rtd. So we host it ourselfs now:

https://docs.inmanta.com/community/latest/

Did you find this link somewhere?

**Comment by cnf** [comment]
Mentioned several times in https://github.com/inmanta/inmanta/blob/master/Readme.md :P
