### ISSUE TITLE
A resource should not be able to define id as fieldname

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#497]

**Comment by wouterdb** [comment]
where is this best to enforce? In the exporter? 

It would seem like a job for the compiler/type checker, but the compiler is not really aware of what is a resource and what is not. 

So either we extend the compiler with a notion of what is a resource or we do the check in the exporter?

**Comment by bartv** [comment]
It should not be possible in the resource definition (python) because the baseclass already has an id that is required

**Comment by wouterdb** [comment]
already fixed
