### ISSUE TITLE
Verify hashes when serving a file

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#532]
The id of the file is that md5sum of its content. Currently the server does not verify the integrity of the file.

**Comment by wouterdb** [comment]
this is fixed for the server side on #545, but perhaps we should also check on the agent side

**Comment by wouterdb** [comment]
fixed for std in https://github.com/inmanta/std/commit/d7bbff8f138a46847784dac2268f959a0626435f

could also be added to handler.py
