### ISSUE TITLE
Compiler server

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#551]
The server needs to be able to compile the source model to be able to orchestrate complex workflows. It forks the compiler as a process whenever required. This model does not work in "development" mode where the server does not have the source code.

This can be solved by introducing a mode that runs the compiler as a "server" and the server requests a new version from the compiler "server". This also enables to run the compile process on another machine than the orchestration server.

- [ ] - Accept and execute compile requests
- [ ] - Project and module manipulation
- [ ] - Queue and or merge compile requests so recompiles are not lost when many changes happen

**Comment by wouterdb** [comment]
what would be the preferred method to link the compiler-server to the main server?
1. configure the server to connect to the compile-server (global or per env)
1. compile server connects to server and server chooses one of the available compile servers (like the agents)
3. command bus (amqp,....)
4. ....

**Comment by bartv** [comment]
For the first use this would be the compiler connecting for the configured env to the server. Like now

```
inmanta export -d
```
but then as a daemon, waiting for recompiles from the server.

Secondary is a scheduler that makes sure that a compiler per env is running. Not sure if that should be in Inmanta or delegated to something like kubernetes, nomad, ...

**Comment by wouterdb** [comment]
so, that would be number two, a mechanism like the agent, that supports both autostart and incoming connections.

**Comment by bartv** [comment]
Closing this one now the compiler slice is implemented.
