### ISSUE TITLE
Introduce += operator for list append

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#587]
The += operator should replace the places where the assignment operator actually indicates the append or extend of the list. Currently = to a relation confuses users because its operator depends on its lhs and rhs arguments.

**Comment by wouterdb** [comment]
List as in relation? I.e. += is just assignment? 

Or list as in attribute?
For list as attribute += would violate the principle that attributes are only assigned once. It would require us to redefine and redesign list attributes entirely.

**Comment by bartv** [comment]
No, for relations. See the updated description.
