### ISSUE TITLE
Iteration over a list of dicts is not supported directly

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#678]
Currently the for implementation uses a dict to store the elements it already evaluated for gradual evaluation. This mechanism fails when the elements in a list are dicts. This is for example possible when working with plugins that do JSON API calls.

A workaround is wrapping all items in a special dict:
```
class ForMap(collections.UserDict, dict):
    def __hash__(self):
        return hash(tuple(self.data.items()))

[ForMap(**item) for item in body]
```

**Comment by wouterdb** [comment]
seems already fixed in https://github.com/inmanta/inmanta/commit/078aeb27580f752e77c94eeb787a3f9d1fbdcd3b
